### ISSUE TITLE
Deprecation: Use ember-copy addon instead of copy method

### ISSUE THREAD

**Issue by Alonski** [kellyselden/ember-datetimepicker#226]
There is a deprecation here:
https://github.com/kellyselden/ember-datetimepicker/blob/master/addon/components/date-time-picker.js#L65

Adding this issue to track it

**Comment by kellyselden** [comment]
Thanks!

**Comment by Alonski** [comment]
@kellyselden I just saw that there is this PR open for almost 3 years :)
This should fix this deprecation no?
https://github.com/kellyselden/ember-datetimepicker/pull/85

**Comment by kellyselden** [comment]
I'm pretty sure the ember bug I linked makes it unable to be removed. It is failing the tests.

**Comment by Alonski** [comment]
Hmm I saw that they closed your bug report. If it is still a bug maybe it should be reopened?

**Comment by kellyselden** [comment]
I just rebased that branch, and it's still broken in 2.18. So we can either wait for that version to age out, or update the import.

**Comment by ericrange** [comment]
did you try this here?
https://deprecations.emberjs.com/v3.x/#toc_ember-runtime-deprecate-copy-copyable

**Comment by Alonski** [comment]
@kellyselden I saw that you dropped 2.18 support.
Does this mean that we can fix this deprecation now?

**Comment by kellyselden** [comment]
@Alonski Done! Thanks for the reminder.
